swagger: '2.0'
info:
  title: Branches
  x-ibm-name: branches
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - proxy:
          title: proxy
          version: 1.0.0
          verb: keep
          target-url: $(target-url)
      - map:
          version: 1.0.0
          title: map
          inputs:
            input:
              schema:
                $ref: '#/definitions/branch'
              variable: request.body
              content: application/json
          outputs:
            output:
              schema:
                type: array
                description: ''
                items:
                  type: object
                  properties:
                    BranchID:
                      type: string
                      name: BranchID
                    BranchType:
                      type: string
                      name: BranchType
                    phone:
                      type: string
                      name: phone
                    address:
                      type: object
                      properties:
                        Address1:
                          type: string
                          name: Address1
                        city:
                          type: string
                          name: city
                        state:
                          type: string
                          name: state
                        ZipCode:
                          type: string
                          name: ZipCode
                      name: address
                example: "[\n\t{\n\t\t\"BranchID\": \"0b3a8cf0-7e78-11e5-8059-a1020f32cce5\",\n\t\t\"BranchType\": \"atm\",\n\t\t\"address\": {\n\t\t\t\"Address1\": \"600 Anton Blvd.\",\n\t\t\t\"Address2\": \"Floor 5\",\n\t\t\t\"city\": \"Costa Mesa\",\n\t\t\t\"state\": \"CA\",\n\t\t\t\"ZipCode\": \"92626\"\n\t\t}\n\t},\n\t{\n\t\t\"BranchID\": \"9d72ece0-7e7b-11e5-9038-55f9f9c08c06\",\n\t\t\"BranchType\": \"atm\",\n\t\t\"address\": {\n\t\t\t\"Address1\": \"4660 La Jolla Village Drive\",\n\t\t\t\"Address2\": \"Suite 300\",\n\t\t\t\"city\": \"San Diego\",\n\t\t\t\"state\": \"CA\",\n\t\t\t\"ZipCode\": \"92122\"\n\t\t}\n\t},\n\t{\n\t\t\"BranchID\": \"ae648760-7e77-11e5-8059-a1020f32cce5\",\n\t\t\"BranchType\": \"atm\",\n\t\t\"address\": {\n\t\t\t\"Address1\": \"New Orchard Road\",\n\t\t\t\"city\": \"Armonk\",\n\t\t\t\"state\": \"NY\",\n\t\t\t\"ZipCode\": \"10504\"\n\t\t}\n\t},\n\t{\n\t\t\"BranchID\": \"c23397f0-7e76-11e5-8059-a1020f32cce5\",\n\t\t\"BranchType\": \"branch\",\n\t\t\"phone\": \"512-286-5000\",\n\t\t\"address\": {\n\t\t\t\"Address1\": \"11400 Burnet Rd.\",\n\t\t\t\"city\": \"Austin\",\n\t\t\t\"state\": \"TX\",\n\t\t\t\"ZipCode\": \"78758-3415\"\n\t\t}\n\t},\n\t{\n\t\t\"BranchID\": \"ca841550-7e77-11e5-8059-a1020f32cce5\",\n\t\t\"BranchType\": \"atm\",\n\t\t\"address\": {\n\t\t\t\"Address1\": \"334 Route 9W\",\n\t\t\t\"city\": \"Palisades\",\n\t\t\t\"state\": \"NY\",\n\t\t\t\"ZipCode\": \"10964\"\n\t\t}\n\t},\n\t{\n\t\t\"BranchID\": \"dc132eb0-7e7b-11e5-9038-55f9f9c08c06\",\n\t\t\"BranchType\": \"branch\",\n\t\t\"phone\": \"978-899-3444\",\n\t\t\"address\": {\n\t\t\t\"Address1\": \"550 King St.\",\n\t\t\t\"city\": \"Littleton\",\n\t\t\t\"state\": \"MA\",\n\t\t\t\"ZipCode\": \"01460-1250\"\n\t\t}\n\t},\n\t{\n\t\t\"BranchID\": \"e1161670-7e76-11e5-8059-a1020f32cce5\",\n\t\t\"BranchType\": \"branch\",\n\t\t\"phone\": \"561-893-7700\",\n\t\t\"address\": {\n\t\t\t\"Address1\": \"5901 Broken Sound Pkwy. NW\",\n\t\t\t\"city\": \"Boca Raton\",\n\t\t\t\"state\": \"FL\",\n\t\t\t\"ZipCode\": \"33487-2773\"\n\t\t}\n\t},\n\t{\n\t\t\"BranchID\": \"f9ca9ab0-7e7b-11e5-9038-55f9f9c08c06\",\n\t\t\"BranchType\": \"atm\",\n\t\t\"address\": {\n\t\t\t\"Address1\": \"1 Rogers Street\",\n\t\t\t\"city\": \"CambrBranchIDge\",\n\t\t\t\"state\": \"MA\",\n\t\t\t\"ZipCode\": \"02142\"\n\t\t}\n\t}\n]"
              variable: message.body
              content: application/json
          actions:
            - set: output.address.Address1
              from:
                - input.address.street1
                - input.address.street2
              value: |-
                var add = $(input.address.street1) ;

                if ($(input.address.street2))
                {
                    add += $(input.address.street2);
                }

                add
            - create: output
              foreach: input
              from: input
              actions:
                - set: BranchType
                  from: type
                - set: BranchID
                  from: id
            - create: output
              foreach: input.address
              from: input.address
              actions:
                - set: address.city
                  from: city
            - set: output.address.ZipCode
              from: input.address.zip_code
              foreach:
                - target: output
                  source: input
            - set: output.address.state
              from: input.address.state
              foreach:
                - target: output
                  source: input.address.state
          options: {}
  properties:
    target-url:
      value: 'https://apictutorials.mybluemix.net/branches'
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
  catalogs: {}
basePath: /branches
paths:
  /details:
    get:
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/branch'
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    options:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
consumes:
  - application/json
definitions:
  branch:
    type: object
    additionalProperties: false
    properties:
      address:
        $ref: '#/definitions/address'
        properties: {}
      type:
        type: string
      id:
        type: string
  address:
    type: object
    additionalProperties: false
    properties:
      street1:
        type: string
      street2:
        type: string
      city:
        type: string
      state:
        type: string
      zip_code:
        type: string
