swagger: '2.0'
info:
  title: schedule-api
  x-ibm-name: schedule-api
  version: 1.0.1
host: $(catalog.host)
schemes:
  - https
basePath: /ibmfhir
produces:
  - application/json
consumes:
  - application/json
security:
  - clientIdHeader: []
    clientSecretHeader: []
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
x-ibm-configuration:
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: (($operationID() = 'Schedule.create'))
              execute:
                - invoke:
                    version: 2.0.0
                    target-url: 'https://$(fhir_host)$(api.operation.path)'
                    username: fhiruser
                    password: Pass@1234
                    verb: keep
            - condition: (($operationID() = 'Schedule.get'))
              execute:
                - invoke:
                    version: 2.0.0
                    target-url: 'https://$(fhir_host)$(api.operation.path)'
                    username: fhiruser
                    password: Pass@1234
                    verb: keep
          otherwise: []
  properties:
    fhir_host:
      value: 'gitlab.prolifics.com:9443/fhir-server/api/v4'
      description: Hostname of the Watson FHIR Server resource
      encoded: false
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
definitions:
  Schedule:
    description: >-
      A container for slots of time that may be available for booking
      appointments.
    properties:
      resourceType:
        description: This is a Schedule resource
        enum:
          - Schedule
      id:
        description: >-
          The logical id of the resource, as used in the URL for the resource.
          Once assigned, this value never changes.
        $ref: '#/definitions/id'
      meta:
        description: >-
          The metadata about the resource. This is content that is maintained by
          the infrastructure. Changes to the content might not always be
          associated with version changes to the resource.
        $ref: '#/definitions/Meta'
      implicitRules:
        description: >-
          A reference to a set of rules that were followed when the resource was
          constructed, and which must be understood when processing the content.
          Often, this is a reference to an implementation guide that defines the
          special rules along with other profiles etc.
        $ref: '#/definitions/uri'
      language:
        description: The base language in which the resource is written.
        $ref: '#/definitions/code'
      text:
        description: >-
          A human-readable narrative that contains a summary of the resource and
          can be used to represent the content of the resource to a human. The
          narrative need not encode all the structured data, but is required to
          contain sufficient detail to make it "clinically safe" for a human to
          just read the narrative. Resource definitions may define what content
          should be represented in the narrative to ensure clinical safety.
        $ref: '#/definitions/Narrative'
      contained:
        description: >-
          These resources do not have an independent existence apart from the
          resource that contains them - they cannot be identified independently,
          and nor can they have their own independent transaction scope.
        items:
          $ref: '#/definitions/ResourceList'
        type: array
      identifier:
        description: External Ids for this item.
        items:
          $ref: '#/definitions/Identifier'
        type: array
      active:
        description: >-
          Whether this schedule record is in active use or should not be used
          (such as was entered in error).
        $ref: '#/definitions/boolean'
      serviceCategory:
        description: >-
          A broad categorization of the service that is to be performed during
          this appointment.
        items:
          $ref: '#/definitions/CodeableConcept'
        type: array
      serviceType:
        description: The specific service that is to be performed during this appointment.
        items:
          $ref: '#/definitions/CodeableConcept'
        type: array
      specialty:
        description: >-
          The specialty of a practitioner that would be required to perform the
          service requested in this appointment.
        items:
          $ref: '#/definitions/CodeableConcept'
        type: array
      actor:
        description: >-
          Slots that reference this schedule resource provide the availability
          details to these referenced resource(s).
        items:
          $ref: '#/definitions/id'
        type: array
      planningHorizon:
        description: >-
          The period of time that the slots that reference this Schedule
          resource cover (even if none exist). These  cover the amount of time
          that an organization's planning horizon; the interval for which they
          are currently accepting appointments. This does not define a
          "template" for planning outside these dates.
        $ref: '#/definitions/Period'
      comment:
        description: >-
          Comments on the availability to describe any extended information.
          Such as custom constraints on the slots that may be associated.
        $ref: '#/definitions/string'
    additionalProperties: false
    required:
      - actor
      - resourceType
  id:
    pattern: '^[A-Za-z0-9\-\.]{1,64}$'
    type: string
    description: >-
      Any combination of letters, numerals, "-" and ".", with a length limit of
      64 characters.  (This might be an integer, an unprefixed OID, UUID or any
      other identifier pattern that meets these constraints.)  Ids are
      case-insensitive.
  Meta:
    description: >-
      The metadata about a resource. This is content in the resource that is
      maintained by the infrastructure. Changes to the content might not always
      be associated with version changes to the resource.
    properties:
      id:
        description: >-
          Unique id for the element within a resource (for internal references).
          This may be any string value that does not contain spaces.
        $ref: '#/definitions/string'
      versionId:
        description: >-
          The version specific identifier, as it appears in the version portion
          of the URL. This value changes when the resource is created, updated,
          or deleted.
        $ref: '#/definitions/id'
      lastUpdated:
        description: When the resource last changed - e.g. when the version changed.
        $ref: '#/definitions/instant'
      source:
        description: >-
          A uri that identifies the source system of the resource. This provides
          a minimal amount of [[[Provenance]]] information that can be used to
          track or differentiate the source of information in the resource. The
          source may identify another FHIR server, document, message, database,
          etc.
        $ref: '#/definitions/uri'
      profile:
        description: >-
          A list of profiles (references to [[[StructureDefinition]]] resources)
          that this resource claims to conform to. The URL is a reference to
          [[[StructureDefinition.url]]].
        items:
          $ref: '#/definitions/canonical'
        type: array
      security:
        description: >-
          Security labels applied to this resource. These tags connect specific
          resources to the overall security policy and infrastructure.
        items:
          $ref: '#/definitions/Coding'
        type: array
      tag:
        description: >-
          Tags applied to this resource. Tags are intended to be used to
          identify and relate resources to process and workflow, and
          applications are not required to consider the tags when interpreting
          the meaning of a resource.
        items:
          $ref: '#/definitions/Coding'
        type: array
    additionalProperties: false
  string:
    pattern: '^[ \r\n\t\S]+$'
    type: string
    description: A sequence of Unicode characters
  instant:
    pattern: >-
      ^([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))$
    type: string
    description: An instant in time - known at least to the second
  uri:
    pattern: ^\S*$
    type: string
    description: String of characters used to identify a name or a resource
  canonical:
    pattern: ^\S*$
    type: string
    description: A URI that is a reference to a canonical URL on a FHIR resource
  Coding:
    description: A reference to a code defined by a terminology system.
    properties:
      id:
        description: >-
          Unique id for the element within a resource (for internal references).
          This may be any string value that does not contain spaces.
        $ref: '#/definitions/string'
      system:
        description: >-
          The identification of the code system that defines the meaning of the
          symbol in the code.
        $ref: '#/definitions/uri'
      version:
        description: >-
          The version of the code system which was used when choosing this code.
          Note that a well-maintained code system does not need the version
          reported, because the meaning of codes is consistent across versions.
          However this cannot consistently be assured, and when the meaning is
          not guaranteed to be consistent, the version SHOULD be exchanged.
        $ref: '#/definitions/string'
      code:
        description: >-
          A symbol in syntax defined by the system. The symbol may be a
          predefined code or an expression in a syntax defined by the coding
          system (e.g. post-coordination).
        $ref: '#/definitions/code'
      display:
        description: >-
          A representation of the meaning of the code in the system, following
          the rules of the system.
        $ref: '#/definitions/string'
      userSelected:
        description: >-
          Indicates that this coding was chosen by a user directly - e.g. off a
          pick list of available items (codes or displays).
        $ref: '#/definitions/boolean'
    additionalProperties: false
  code:
    pattern: '^[^\s]+(\s[^\s]+)*$'
    type: string
    description: >-
      A string which has at least one character and no leading or trailing
      whitespace and where there is no whitespace other than single spaces in
      the contents
  boolean:
    pattern: ^true|false$
    type: boolean
    description: Value of "true" or "false"
  Narrative:
    description: >-
      A human-readable summary of the resource conveying the essential clinical
      and business information for the resource.
    properties:
      id:
        description: >-
          Unique id for the element within a resource (for internal references).
          This may be any string value that does not contain spaces.
        $ref: '#/definitions/string'
      status:
        description: >-
          The status of the narrative - whether it's entirely generated (from
          just the defined data or the extensions too), or whether a human
          authored it and it may contain additional data.
        enum:
          - generated
          - extensions
          - additional
          - empty
      div:
        description: 'The actual narrative content, a stripped down version of XHTML.'
        $ref: '#/definitions/xhtml'
    additionalProperties: false
    required:
      - div
  xhtml:
    description: xhtml - escaped html (see specfication)
  Identifier:
    description: >-
      An identifier - identifies some entity uniquely and unambiguously.
      Typically this is used for business identifiers.
    properties:
      id:
        description: >-
          Unique id for the element within a resource (for internal references).
          This may be any string value that does not contain spaces.
        $ref: '#/definitions/string'
      use:
        description: The purpose of this identifier.
        enum:
          - usual
          - official
          - temp
          - secondary
          - old
      type:
        description: >-
          A coded type for the identifier that can be used to determine which
          identifier to use for a specific purpose.
        $ref: '#/definitions/CodeableConcept'
      system:
        description: >-
          Establishes the namespace for the value - that is, a URL that
          describes a set values that are unique.
        $ref: '#/definitions/uri'
      value:
        description: >-
          The portion of the identifier typically relevant to the user and which
          is unique within the context of the system.
        $ref: '#/definitions/string'
      period:
        description: Time period during which identifier is/was valid for use.
        $ref: '#/definitions/Period'
      assigner:
        description: Organization that issued/manages the identifier.
        $ref: '#/definitions/id'
    additionalProperties: false
  CodeableConcept:
    description: >-
      A concept that may be defined by a formal reference to a terminology or
      ontology or may be provided by text.
    properties:
      id:
        description: >-
          Unique id for the element within a resource (for internal references).
          This may be any string value that does not contain spaces.
        $ref: '#/definitions/string'
      coding:
        description: A reference to a code defined by a terminology system.
        items:
          $ref: '#/definitions/Coding'
        type: array
      text:
        description: >-
          A human language representation of the concept as
          seen/selected/uttered by the user who entered the data and/or which
          represents the intended meaning of the user.
        $ref: '#/definitions/string'
    additionalProperties: false
  Period:
    description: A time period defined by a start and end date and optionally time.
    properties:
      id:
        description: >-
          Unique id for the element within a resource (for internal references).
          This may be any string value that does not contain spaces.
        $ref: '#/definitions/string'
      start:
        description: The start of the period. The boundary is inclusive.
        $ref: '#/definitions/dateTime'
      end:
        description: >-
          The end of the period. If the end of the period is missing, it means
          no end was known or planned at the time the instance was created. The
          start may be in the past, and the end date in the future, which means
          that period is expected/planned to end at that time.
        $ref: '#/definitions/dateTime'
    additionalProperties: false
  dateTime:
    pattern: >-
      ^([0-9]([0-9]([0-9][1-9]|[1-9]0)|[1-9]00)|[1-9]000)(-(0[1-9]|1[0-2])(-(0[1-9]|[1-2][0-9]|3[0-1])(T([01][0-9]|2[0-3]):[0-5][0-9]:([0-5][0-9]|60)(\.[0-9]+)?(Z|(\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00)))?)?)?$
    type: string
    description: >-
      A date, date-time or partial date (e.g. just year or year + month).  If
      hours and minutes are specified, a time zone SHALL be populated. The
      format is a union of the schema types gYear, gYearMonth, date and
      dateTime. Seconds must be provided due to schema type constraints but may
      be zero-filled and may be ignored.                 Dates SHALL be valid
      dates.
  ResourceList:
    $ref: '#/definitions/Schedule'
paths:
  '/Schedule/{ScheduleId}':
    get:
      operationId: Schedule.get
      responses:
        '200':
          description: 200 OK
      parameters:
        - name: ScheduleId
          type: string
          required: true
          in: path
  /Schedule:
    post:
      tags:
        - Schedule
      summary: Create a new instance of the model and persist it into the data source.
      operationId: Schedule.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Schedule'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Schedule'
      deprecated: false
    put:
      tags:
        - Schedule
      summary: >-
        Patch an existing model instance or insert a new one into the data
        source.
      operationId: Schedule.upsert__put_Schedules
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Schedule'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Schedule'
      deprecated: false
    patch:
      tags:
        - Schedule
      summary: >-
        Patch an existing model instance or insert a new one into the data
        source.
      operationId: Schedule.upsert__patch_Schedules
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Schedule'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Schedule'
      deprecated: false
